Product page
faridafaqiri/product-landing-page pull request #1
Opened 2024-05-29 08:09 UTC by faridafaqiri

### In this project I did these works:
-Added index.html and style.css file.
-Setup linters.
-Added header and section tag into body tag.
-Added div tag img, nav, iframe and some other tag in html file.
-I designed my web page by css property.
-I added description in README.md file.

2024-05-30 19:43 UTC, ahzamir requested changes
### Hi @faridafaqiri 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Copy your HTML file code and paste it to the freecodecamp website Product Landing Page project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

- Also check the inline comments below

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
![image](https://github.com/faridafaqiri/product-landing-page/assets/96838030/8e1a6614-3787-4848-ac67-2c4295a5c62a)

✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Product Landing Page and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your project has a professional README.md file
❌Your project code is clean

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-30 19:43 UTC, ahzamir commented on product.html
Your HTML code is not clean and properly aligned. Please use 2 spaces for indentation instead of 1-3-4. Additionally, ensure that child elements are properly indented under their parent elements. Here's an example to help you:

**Incorrect:**
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
  <h1>This is a Heading</h1>
        <p>This is a paragraph.</p>
    </body>
</html>
```

**Correct:**
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>
    <h1>This is a Heading</h1>
    <p>This is a paragraph.</p>
  </body>
</html>
```

**Rule:** Each child element should be indented 2 spaces under its parent element for better readability and maintainability.
**Hint**: Go to the VSCode bottom right corner, you can see "Spaces: 4" (or a similar indicator). Click on that, then click on "Indent Using Spaces" and select 2. You can also use the gray color column lines to help you know where your parent and child elements should be.

2024-05-30 19:43 UTC, ahzamir commented on product.html
> +        <a href="#FREE_DELIVERY">FREE DELIVERY</a>
- Try to use the actual ids of these specific sections so your nav links work.

2024-05-30 19:43 UTC, ahzamir commented on product.html
- Your HTML code is missing some of the freecodecamp requirements check it there.

2024-05-31 04:58 UTC, faridafaqiri commented on product.html
@ahzamir 
Hi! thank you for your available feedback.
I will use this feedback in my future projects and have also made the necessary changes.

2024-06-02 05:57 UTC, faridafaqiri commented on product.html
@ahzamir  
HI! 
first of all thank your available feedback.
I cleaned my html code and followed and completed all requirements. 
![Uploading pro.JPG…]()

2024-06-02 12:32 UTC, ahzamir requested changes
@faridafaqiri  Check your codes from start to end and solve the spacing issues.

2024-06-02 12:32 UTC, ahzamir commented on product.html
- Still, your HTML code is not clean, your opening and closing tag should be in the same line OR should be in the same column line spacing.
  - Some divs don't have a closing tag or are incorrectly aligned.

2024-06-02 13:23 UTC, faridafaqiri commented on product.html
@ahzamir 
sorry for mistake 
I formatted my html code.
can you please give me feedback again and if its correct please approved.

2024-06-04 18:19 UTC, ahzamir approved these changes
### Hi @faridafaqiri 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍

![image](https://github.com/faridafaqiri/product-landing-page/assets/96838030/8e1a6614-3787-4848-ac67-2c4295a5c62a)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Product Landing Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-04 18:21 UTC, ahzamir commented
@faridafaqiri 

- Deploy your project and help your partner to finish her projects!

2024-06-05 04:17 UTC, merged